### ISSUE TITLE
ArcPlates GUI Dupe

### ISSUE THREAD

**Issue by hutchy50** [BrendonCurmi/FusionPixelmon#1]
When left clicking to equip a plate it doesn't block you from also right clicking to return it to your inventory, so it both equips and returns it, duping the plate

Versions:
Sponge 7.2.0
Forge 2847
Pixelmon 7.2.2

**Comment by BrendonCurmi** [comment]
Issue is now resolved in PR #2 and will be added to v1.3 on https://ore.spongepowered.org/FusionDev/FusionPixelmon/versions thanks :) 👍
