### ISSUE TITLE
Another Dupe Bug

### ISSUE THREAD

**Issue by ItsCg** [BrendonCurmi/FusionPixelmon#10]
Sorry. Just 2 more I found. You should create a discord and make a bug channel, unless you prefer it done here. Thanks for fixing / adding configs btw.

**1** -  Spamming right click and removing the plate from /arc has a chance to duplicate it. Not sure if it's the server performance or the mod doing that. - https://gfycat.com/kaleidoscopicpointedamethystinepython

**2** - Has to do with Inventory Tweaks. Not sure if this could be patched or not. 
Sorting the /arc inventory with 2 plates stored causes a dupable plate. Which can be taken out using right click every second. - https://gfycat.com/agreeablenextamericanwarmblood

FusionPixelmon = 1.5
Sponge = 7.1.10
Forge = 2838
Pixelmon = 7.2.2

**Comment by BrendonCurmi** [comment]
Hey, thanks :) Great idea! I've created a discord, let me know if you can access it: https://discord.gg/VFNTycm we can address these bugs there

**Comment by BrendonCurmi** [comment]
1. I've increased the timeout to 900 milliseconds so if the issue persists, it's probably caused due to server performance
2. I've added this to a "Known Issues" section since to mitigate it would require updating every slot which would be suboptimal for all users
Thanks :)
