### ISSUE TITLE
[Suggestion] Multi economy support

### ISSUE THREAD

**Issue by delsolsi** [BrendonCurmi/FusionPixelmon#16]
Config option to select our economy, i want to use a different economy i created via economy lite for pokemon editing etc, would be nice if you added a config option for it.

**Comment by BrendonCurmi** [comment]
Thanks for the suggestion. I now wrote the service in #17 and implemented in #18 
It will allow you to choose whether to use PokeDollars or the default currency through an economy plugin like economylite.
It will be included in the next release, so keep an eye on [Ore](https://ore.spongepowered.org/FusionDev/FusionPixelmon) or get notified on the [discord](https://discord.gg/VFNTycm)
Thanks :)

**Comment by delsolsi** [comment]
hello, thanks for adding that however thats not what i suggested, the way you implemented it doesnt let you select what currency you want to use, see some servers use pokedollars as the default currency and add their own secondary currency called, pokebuilder, crystals, gems etc, thats what i  suggested a config option to add our own  currency name to be used with pokedesigner.

**Comment by BrendonCurmi** [comment]
Hello, got it. Pushing PR #20 to add this configuration:
```
    # The currency used in the PokeDesigner.
    # Example: "pokedollar"
    shop-currency=coin
```

Now it'll be possible to use pokedollars or a specific currency, which you can specify. If the currency isn't found, it'll fallback to the default currency

Pushing it to a new release v1.9

Thanks
