### ISSUE TITLE
Pixelmon Generations Support

### ISSUE THREAD

**Issue by Gottr** [BrendonCurmi/FusionPixelmon#25]
Hey I was wondering whether you'd be able/willing to add support for Pixelmon Generations to this mod. Haven't been able to find any good sidemods/plugins that contain a pokebuilder and work with Pixelmon Generations, however; FusionPixelmon looks great and I'd love to be able to use it on a Generations server.

**Comment by VOrlando520** [comment]
That requires supporting two separate code bases because gens uses an old pixelmon base from reforged. not worth it in the end

**Comment by BrendonCurmi** [comment]
Hey @Gottr thanks, as @VOrlando520 correctly said, it would require supporting 2 separate pixelmon code bases. Currently busy with rewriting the plugin to migrate it to Spigot. Once done, I'd be willing to look into adding support for Generations. Personally I'd recommend using Pixelmon Reforged as it gets regular updates, has better performance, and great support team on discord. You could join our [discord](https://discord.gg/VFNTycm) to stay updated on progress and info if I'd be migrating to Gen

**Comment by Gottr** [comment]
Sounds great, thanks for your time
