### ISSUE TITLE
GriefPrevention duplication glitch (Right click shrine)

### ISSUE THREAD

**Issue by screm11** [BrendonCurmi/FusionPixelmon#27]
This may also work with other region management plugins - but with GriefPrevention if you attempt to right click a shrine in a player claimed area (Player shrines) you are able to pickup an infinite amount since it doesn't remove it from the world due to protection and still  gives you the item.
If it'd be possible, maybe check if the region is protected then cancel the pickup?

**Comment by screm11** [comment]
I forgot to add Bug to the post ;-; sorry

**Comment by BrendonCurmi** [comment]
Hi @screm11 thanks for opening this and bringing it to my attention. It will be a bit difficult to check if the region is protected, as that would require dependencies on faction plugins which would be very specific. So instead I've implemented a feature that allows players to lock shrines from being picked up. They can still be used, but cant be picked up by another player if it's locked. Thanks #32
