### ISSUE TITLE
Picking up a shrine / config in the future?

### ISSUE THREAD

**Issue by ItsCg** [BrendonCurmi/FusionPixelmon#3]
Bug?
- Seems like when your inventory is full, you can't pick up any shrines. Even if your hotbar has empty slots, it won't pick them up. 
![Screenshot_939](https://user-images.githubusercontent.com/63455487/78990846-1ec89d80-7afd-11ea-9401-cd9ec64cadd8.png)

Rest of these are just suggestions, sorry if this shouldn't be here.

- Will configs be available in the future? Such as disabling certain things like making pokemon shiny, level buying.. etc?

- Also, permissions are needed for luckperms if you could provide those in the docs.

Sponge = 7.1.10
Forge = 2838
Pixelmon = 7.2.2

**Comment by BrendonCurmi** [comment]
Thanks for opening this. The inventory bug and documentation requests are resolved in PR #4 which I'll push to a new version after deciding what to do with configs. Do you intend on having config variables for each major feature (picking up shrines, antifall, etc) or for details like which shops will be available?

**Comment by iJaySin** [comment]
Not OP but it would be nice if we can have a config to disable both any major feature and specific shops like IVs/EVs.

**Comment by ItsCg** [comment]
Yeah so I personally use apritree so I would disable the masterball recipe feature as an example. So having a variable as true/false for major and individual shop things would be nice. 

Shop {
Shiny=False
Nature=False
}
Etc.

Sorry, i’m not experienced with coding. Just what I typically see in config settings. Not sure if you could do that, but it’d be a nice feature. Thanks ^^

**Comment by Barrybasher** [comment]
Is there anyway to alter the prices for pokebuilder? if not that would be nice to add to the configs

**Comment by BrendonCurmi** [comment]
Hey thanks for opening. I've now implemented modifiable config files as part of PR #7 which will be added to the new version, so keep an eye on https://ore.spongepowered.org/FusionDev/FusionPixelmon for new releases

The config file will allow you to enable/disable major features and to modify which shops you want active and the prices. It'll be explained here: https://github.com/BrendonCurmi/FusionPixelmon/#Config
