### ISSUE TITLE
Just an idea

### ISSUE THREAD

**Issue by LluviaWolf** [BrendonCurmi/FusionPixelmon#34]
Hey this Plugin is really great and I love it a lot !
I was curious if you maybe are able to add some kind of /givemodifier command so that Admins can add certain modifiers to maybe Crates as winner loot, and let players sell their modifiers in the GTS if they do not want them.
Would something like this be possible ?

Kindest regards Lluvia

**Comment by BrendonCurmi** [comment]
Hey Lluvia, thanks, glad you like the plugin! :) 
This plugin doesnt have modifiers or crates, so could you please explain how these modifiers would work?
Thanks in advance

**Comment by LluviaWolf** [comment]
I meant as in that you can give players an item so they can change one specific thing (example Gender) for there Pixelmon and that the Item then disappears from there inventory (it gets consumed). Kinda like PokeBuilder. 

Examples:

Netherstar(Renamed to Shiny Token) could be used to make your Pixelmon Shiny
Egg(Renamed to Gender Token) could be used to change your Pixelmons Gender
Pokeball(Renamed to Pokeball Token) could be used to change the Pokeball of you Pixelmon
Feather(Renamed to Growth Token) could be used to change the Growth of your Pixelmon
and so on

And that Admins can use a command like /givetoken NAMEOFTOKEN to get that Token so they can give it to Players as Rewards or put the in Crates from Huskycrates for example

Hope you understand what I'm trying to say now :P
