### ISSUE TITLE
Not working on Pixelmon Reforged 8.1.2

### ISSUE THREAD

**Issue by M4RC0Sx** [BrendonCurmi/FusionPixelmon#39]
Latest release on sponge of FusionPixelmon isn´t working on 8.1.2

**Comment by BrendonCurmi** [comment]
Hi, thanks. The next release FusionPixelmon 1.10 will work on Pixelmon 8.1.2
You should join our discord to get notified when 1.10 comes out https://discord.gg/VFNTycm
Thanks :)
