### ISSUE TITLE
Move price incorrect

### ISSUE THREAD

**Issue by zThana** [BrendonCurmi/FusionPixelmon#48]
The price for modifying moves is not set to what we have set it to within the configuration file.

```
move {
    enabled=true
    prices {
        # Price for changing a Move.
        change-move=2500
    }
}
```

![image](https://user-images.githubusercontent.com/8803519/97046882-5f0edb00-1578-11eb-8bcf-d19d51b4a62f.png)

**Comment by BrendonCurmi** [comment]
Hi, thanks for letting me know :) This will be fixed in the next version. You can join our discord to be notified when it's released: https://discord.gg/VFNTycm Thanks!
