### ISSUE TITLE
Issue with arc command

### ISSUE THREAD

**Issue by Barrybasher** [BrendonCurmi/FusionPixelmon#5]
Hi, would just like to say from the start amazing plugin! I run a small server mostly for a couple friends and there kids and been having a tough time finding these types of plugins that the bigger servers have, so much appriciated! the issue i am having is /pd works amazing but when I do /arc it just opens the pokebuilder menu aswell, I have tried it with just the arc permissions and no pd permissions and its the same thing, not sure if i am doing something wrong? if i am or cant be solved its fine as very happy having the pokebuilder feature (without having to make my own one and my one being alot worse xD)

**Comment by iJaySin** [comment]
When you do /arc, does it say "Arceus Selector" or "Pokemon Selector"? They have the same GUI when you use either /arc or /pd but have different titles. I just wanna input that I don't have a problem with /arc.

**Comment by Barrybasher** [comment]
you are 100 percent right, it was just me being dumb! I just scim read the feature and thought it was to hold the plates ready to use on chalice not for switching the held item

**Comment by BrendonCurmi** [comment]
Hi @Barrybasher , thanks! Glad you like the plugin :) <3
Thanks for your help on this @iJaySin 
As @iJaySin correctly said, both /pd and /arc bring up a similar Poke Selector GUI. "Pokemon Selector" for /pd for any poke, and "Arceus Selector" for /arc to choose an Arceus. As the plate data needs to be with an Arceus entity, it's not used to hold plates for a Chalice. But once youve found them all and activate the chalice and get your Arceus, you can save new plates and easily switch them through the /arc menu :)
