### ISSUE TITLE
Crashes on server

### ISSUE THREAD

**Issue by Freedom16789** [BrendonCurmi/FusionPixelmon#58]
this is the log from the sever i have all the right stuff to run it and still not working
[2020-12-23-4.log](https://github.com/BrendonCurmi/FusionPixelmon/files/5736402/2020-12-23-4.log)

**Comment by BrendonCurmi** [comment]
The Forge mod is for singleplayer use, not multiplayer use (on a server). Use the Sponge or Spigot plugins instead for multiplayer use on a server
https://github.com/BrendonCurmi/FusionPixelmon/tree/master/fusionpixelmon-forge
![image](https://user-images.githubusercontent.com/40634809/103024149-90dbf800-454f-11eb-9684-e5a01fe63620.png)
