### ISSUE TITLE
Commands don't work

### ISSUE THREAD

**Issue by DanDragonWolf** [BrendonCurmi/FusionPixelmon#68]
I can't use any of the commands. I looked in my logs and saw this error: [https://pastebin.com/NGgdLpuB](https://pastebin.com/NGgdLpuB)

**Comment by DanDragonWolf** [comment]
It fixed when I downloaded Gooeylib 1.0.6 instead of 2.1.0

**Comment by BrendonCurmi** [comment]
Cool. GooeyLibs v1.0.5 is the last tested version. Thanks
