### ISSUE TITLE
Arc Dupe

### ISSUE THREAD

**Issue by ItsCg** [BrendonCurmi/FusionPixelmon#8]
Shift right clicking plates duplicates them in the hotbar section of your inventory. 

Sponge 7.1.10
Forge 2838
Pixelmon 7.2.2

Edit : https://gfycat.com/perkyagonizingcrocodileskink

**Comment by BrendonCurmi** [comment]
Hey, thanks for raising :) This is now fixed in PR #9 which I'll hotfix to a new version on https://ore.spongepowered.org/FusionDev/FusionPixelmon - Thanks a lot!
